### ISSUE TITLE
Error executing action `apply` on resource 'sysctl_param[kernel.mm.transparent_hugepage.defrag]'

### ISSUE THREAD

**Issue by heaven** [sous-chefs/sysctl#102]
The trace:
```
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of sysctl -w "kernel.mm.transparent_hugepage.defrag=never" ----
    STDOUT:
    STDERR: sysctl: cannot stat /proc/sys/kernel/mm/transparent_hugepage/defrag: No such file or directory
    ---- End output of sysctl -w "kernel.mm.transparent_hugepage.defrag=never" ----
    Ran sysctl -w "kernel.mm.transparent_hugepage.defrag=never" returned 255

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sysctl/libraries/helpers_param.rb:62:in `set_sysctl_param'
    /var/chef/cache/cookbooks/sysctl/libraries/sysctl_param.rb:68:in `block (2 levels) in <class:SysctlParam>'
    /var/chef/cache/cookbooks/sysctl/libraries/sysctl_param.rb:64:in `block in <class:SysctlParam>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/sysctl/recipes/default.rb

     26:   sysctl_param k do
     27:     value v
     28:   end
     29: end if node.attribute?('sysctl') && node['sysctl'].attribute?('params')

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/sysctl/recipes/default.rb:26:in `block in from_file'

    sysctl_param("kernel.mm.transparent_hugepage.defrag") do
      action [:apply]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :sysctl_param
      cookbook_name "sysctl"
      recipe_name "default"
      value "never"
      key "kernel.mm.transparent_hugepage.defrag"
    end

    System Info:
    ------------
    chef_version=12.21.26
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]
    program_name=chef-client worker: ppid=6907;start=13:34:53;
    executable=/opt/chef/bin/chef-client
```

I found that it tries to modify
`/proc/sys/kernel/mm/transparent_hugepage/defrag`
while the correct path is
`/sys/kernel/mm/transparent_hugepage/defrag`

**Comment by svanzoest** [comment]
Hi!,

the sysctl cookbook currently  does not manage `/etc/sysfs.conf` and `/sys`. It focuses on `sysctl` and `/proc/sys`. It looks like there  are some cookbooks on [supermarket](https://supermarket.chef.io/cookbooks?q=sysfs)  that may solve your need.
